language: php

php:
    - 7.0
    - nightly

env:
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=dev-master

before_script:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION}

script: phpunit --coverage-text

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master
        - php: nightly
